spring:
  redis:
    database: 1
    host: 127.0.0.1
  application:
    name: t-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    username: root
    password: AI123456
    url: jdbc:mysql://127.0.0.1:3306/t_pan?characterEncoding=utf8&serverTimeZone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.tangl.pan
  title: t-pan-server docs
  description: t-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: tangl
  contact-url: t.bright.top
  contact-email: tl-bright@163.com
  version: 1.0
