spring:
  application:
    name: t-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.tangl.pan
  title: t-pan-server docs
  description: t-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: tangl
  contact-url: t.bright.top
  contact-email: tl-bright@163.com
  version: 1.0

logging:
  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO